spring:
  application:
    name: summat

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=summat
    username: summat_admin
    password: summat_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
        default_schema: summat

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#    root: DEBUG  # 필요 시 활성화

jwt:
  secret: "this-is-a-very-long-secret-key-for-jwt-hs256-1234567890"
#  access-validity-ms: 20000      # 20초 테스트용
  access-validity-ms: 3600000      # 1시간
  refresh-validity-ms: 604800000   # 7일

file:
  upload-dir: /Users/chokyeil/summat/uploads